# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lc-nbdev',
                'doc_host': 'https://RyanLWhite.github.io',
                'git_url': 'https://github.com/RyanLWhite/lc-nbdev',
                'lib_path': 'lc'},
  'syms': {'lc.core': {'lc.core.foo': ('core.html#foo', 'lc/core.py')}}}
